---
output: pdf_document
header-includes:
- \usepackage[french]{babel}
- \usepackage{float}
- \usepackage{titling}
---
\begin{titlingpage}
  \rightline{Équipe 2}
  \centering
  \Large
  Travail fait par \\
  \vspace{1cm}
  \text{Matis Brassard-Verrier (111 182 740) }\\
  \text{Alyson Marquis (111 183 605)}\\
  \text{Alexis Picard (111 182 200)}\\
  \text{Samuel Provencher (111 181 794)}\\
  \vfill
  \Large
  Apprentissage statistique en actuariat \\
  \vspace{0.5cm}
  \text{ACT-3114}
  \vfill
  \Large
  Rapport 1\\
  \vfill
  \Large
  Présenté à\\
  \vspace{0.5cm}
  \text{Marie-Pier Côté}
  \vfill
  \Large
  École d'actuariat\\
  \text{Université Laval}\\
  \text{27 février 2020}
\end{titlingpage}

\tableofcontents
\newpage
\section{Introduction}
Dans le cadre du travail,

\newpage
\section{Analyse exploratoire des données}
Tout d'abord, afin de bien comprendre la base de données choisie, une analyse exploratoire des données est nécessaire. La présente section traite des erreurs décelées dans le jeu de données et fournit les informations pertinentes sur les variables exogènes ainsi que sur la variable réponse.

La visualisation des données à l'étude a permis de déceler quelques erreurs. Tout d'abord, $10$ observations avaient un nombre de salle de bain égal à $0$. Étant donné qu'il est impossible d'avoir une maison sans salle de bain et que ces observations représentent qu'un faible pourcentage du jeu de données, il a été convenu de supprimer ces $10$ observations. De plus, une observation avait $33$ chambres. En se fiant à l'aire habitable de la maison ainsi qu'aux nombre de salles de bain de cette maison, il a été convenu que le nombre de chambres avait subi une erreur de frappe. C'est pourquoi le nombre de chambres pour cette observation a été mis à $3$. 

- Nb de chambres à 0
- Année de maison à 1900

\newpage
\section{Autres sections ?}

\newpage
\section{Conclusion}

\newpage
\section{Bibliographie}

\newpage
\section{Annexe}
— **Le nom du jeu de données**

kc_house_sales (House sales in King County, USA)

— **La source**

https://www.kaggle.com/harlfoxem/housesalesprediction

— **Une brève description des données (environ deux phrases)**

Cet ensemble de données contient les prix de vente des maisons pour « King County », qui comprend Seattle. Il comprend les maisons vendues entre mai 2014 et mai 2015.

— **La variable réponse et son type**

« House sales » (prix de vente des maisons) -Variable numérique continue

— **La mesure d’exposition (s’il n’y en a pas, le mentionner)**

Il n’y en a pas

— **Cinq variables explicatives et leur type**

Bedrooms : Nombre de chambres – Variable numérique discrète

Bathrooms : Nombre de salles de bain (0.5 est une toilette sans douche) - Variable numérique continue

sqft_living : Superficie de l’espace de vie en pieds carrés - Variable numérique discrète

sqft_lot : Superficie du terrain en pieds carrés - Variable numérique discrète

floors : Nombre d'étages - Variable numérique continue

et plusieurs autres variables bien sur!

— **La taille du jeu de données (nombre d’observations et de variables)**

21 613 lignes pour 21 colonnes (variables)

